production:
  database: books_production
  host: localhost
  adapter: sqlite
  user:
  password:

development:
  database: books_dev
  host: localhost
  adapter: sqlite
  user:
  password:

test:
  database: books_test
  host: localhost
  adapter: sqlite
  user:
  password:

